//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLXJ.Service2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="model", Namespace="WebService1")]
    [System.SerializableAttribute()]
    public partial class model : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WebService1", ConfigurationName="Service2.Service2Soap")]
    public interface Service2Soap {
        
        // CODEGEN: 命名空间 WebService1 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="WebService1/HelloWorld", ReplyAction="*")]
        testLXJ.Service2.HelloWorldResponse HelloWorld(testLXJ.Service2.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 WebService1 的元素名称 GetModelResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="WebService1/GetModel", ReplyAction="*")]
        testLXJ.Service2.GetModelResponse GetModel(testLXJ.Service2.GetModelRequest request);
        
        // CODEGEN: 命名空间 WebService1 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="WebService1/GetModelById", ReplyAction="*")]
        testLXJ.Service2.GetModelByIdResponse GetModelById(testLXJ.Service2.GetModelByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="WebService1", Order=0)]
        public testLXJ.Service2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(testLXJ.Service2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="WebService1", Order=0)]
        public testLXJ.Service2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(testLXJ.Service2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebService1")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModel", Namespace="WebService1", Order=0)]
        public testLXJ.Service2.GetModelRequestBody Body;
        
        public GetModelRequest() {
        }
        
        public GetModelRequest(testLXJ.Service2.GetModelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetModelRequestBody {
        
        public GetModelRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModelResponse", Namespace="WebService1", Order=0)]
        public testLXJ.Service2.GetModelResponseBody Body;
        
        public GetModelResponse() {
        }
        
        public GetModelResponse(testLXJ.Service2.GetModelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebService1")]
    public partial class GetModelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public testLXJ.Service2.model GetModelResult;
        
        public GetModelResponseBody() {
        }
        
        public GetModelResponseBody(testLXJ.Service2.model GetModelResult) {
            this.GetModelResult = GetModelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModelById", Namespace="WebService1", Order=0)]
        public testLXJ.Service2.GetModelByIdRequestBody Body;
        
        public GetModelByIdRequest() {
        }
        
        public GetModelByIdRequest(testLXJ.Service2.GetModelByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebService1")]
    public partial class GetModelByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetModelByIdRequestBody() {
        }
        
        public GetModelByIdRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModelByIdResponse", Namespace="WebService1", Order=0)]
        public testLXJ.Service2.GetModelByIdResponseBody Body;
        
        public GetModelByIdResponse() {
        }
        
        public GetModelByIdResponse(testLXJ.Service2.GetModelByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebService1")]
    public partial class GetModelByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public testLXJ.Service2.model GetModelByIdResult;
        
        public GetModelByIdResponseBody() {
        }
        
        public GetModelByIdResponseBody(testLXJ.Service2.model GetModelByIdResult) {
            this.GetModelByIdResult = GetModelByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service2SoapChannel : testLXJ.Service2.Service2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2SoapClient : System.ServiceModel.ClientBase<testLXJ.Service2.Service2Soap>, testLXJ.Service2.Service2Soap {
        
        public Service2SoapClient() {
        }
        
        public Service2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testLXJ.Service2.HelloWorldResponse testLXJ.Service2.Service2Soap.HelloWorld(testLXJ.Service2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            testLXJ.Service2.HelloWorldRequest inValue = new testLXJ.Service2.HelloWorldRequest();
            inValue.Body = new testLXJ.Service2.HelloWorldRequestBody();
            testLXJ.Service2.HelloWorldResponse retVal = ((testLXJ.Service2.Service2Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testLXJ.Service2.GetModelResponse testLXJ.Service2.Service2Soap.GetModel(testLXJ.Service2.GetModelRequest request) {
            return base.Channel.GetModel(request);
        }
        
        public testLXJ.Service2.model GetModel() {
            testLXJ.Service2.GetModelRequest inValue = new testLXJ.Service2.GetModelRequest();
            inValue.Body = new testLXJ.Service2.GetModelRequestBody();
            testLXJ.Service2.GetModelResponse retVal = ((testLXJ.Service2.Service2Soap)(this)).GetModel(inValue);
            return retVal.Body.GetModelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testLXJ.Service2.GetModelByIdResponse testLXJ.Service2.Service2Soap.GetModelById(testLXJ.Service2.GetModelByIdRequest request) {
            return base.Channel.GetModelById(request);
        }
        
        public testLXJ.Service2.model GetModelById(string id) {
            testLXJ.Service2.GetModelByIdRequest inValue = new testLXJ.Service2.GetModelByIdRequest();
            inValue.Body = new testLXJ.Service2.GetModelByIdRequestBody();
            inValue.Body.id = id;
            testLXJ.Service2.GetModelByIdResponse retVal = ((testLXJ.Service2.Service2Soap)(this)).GetModelById(inValue);
            return retVal.Body.GetModelByIdResult;
        }
    }
}
