//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testLXJ.PassportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PassportService.PassportServiceSoap")]
    public interface PassportServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        testLXJ.PassportService.HelloWorldResponse HelloWorld(testLXJ.PassportService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredenceByToken", ReplyAction="*")]
        testLXJ.PassportService.GetCredenceByTokenResponse GetCredenceByToken(testLXJ.PassportService.GetCredenceByTokenRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearPCert", ReplyAction="*")]
        testLXJ.PassportService.ClearPCertResponse ClearPCert(testLXJ.PassportService.ClearPCertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public testLXJ.PassportService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(testLXJ.PassportService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public testLXJ.PassportService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(testLXJ.PassportService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCredenceByTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredenceByToken", Namespace="http://tempuri.org/", Order=0)]
        public testLXJ.PassportService.GetCredenceByTokenRequestBody Body;
        
        public GetCredenceByTokenRequest() {
        }
        
        public GetCredenceByTokenRequest(testLXJ.PassportService.GetCredenceByTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCredenceByTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public GetCredenceByTokenRequestBody() {
        }
        
        public GetCredenceByTokenRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCredenceByTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredenceByTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public testLXJ.PassportService.GetCredenceByTokenResponseBody Body;
        
        public GetCredenceByTokenResponse() {
        }
        
        public GetCredenceByTokenResponse(testLXJ.PassportService.GetCredenceByTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCredenceByTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetCredenceByTokenResult;
        
        public GetCredenceByTokenResponseBody() {
        }
        
        public GetCredenceByTokenResponseBody(object GetCredenceByTokenResult) {
            this.GetCredenceByTokenResult = GetCredenceByTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearPCertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearPCert", Namespace="http://tempuri.org/", Order=0)]
        public testLXJ.PassportService.ClearPCertRequestBody Body;
        
        public ClearPCertRequest() {
        }
        
        public ClearPCertRequest(testLXJ.PassportService.ClearPCertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClearPCertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public ClearPCertRequestBody() {
        }
        
        public ClearPCertRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearPCertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearPCertResponse", Namespace="http://tempuri.org/", Order=0)]
        public testLXJ.PassportService.ClearPCertResponseBody Body;
        
        public ClearPCertResponse() {
        }
        
        public ClearPCertResponse(testLXJ.PassportService.ClearPCertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ClearPCertResponseBody {
        
        public ClearPCertResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PassportServiceSoapChannel : testLXJ.PassportService.PassportServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassportServiceSoapClient : System.ServiceModel.ClientBase<testLXJ.PassportService.PassportServiceSoap>, testLXJ.PassportService.PassportServiceSoap {
        
        public PassportServiceSoapClient() {
        }
        
        public PassportServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassportServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassportServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testLXJ.PassportService.HelloWorldResponse testLXJ.PassportService.PassportServiceSoap.HelloWorld(testLXJ.PassportService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            testLXJ.PassportService.HelloWorldRequest inValue = new testLXJ.PassportService.HelloWorldRequest();
            inValue.Body = new testLXJ.PassportService.HelloWorldRequestBody();
            testLXJ.PassportService.HelloWorldResponse retVal = ((testLXJ.PassportService.PassportServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testLXJ.PassportService.GetCredenceByTokenResponse testLXJ.PassportService.PassportServiceSoap.GetCredenceByToken(testLXJ.PassportService.GetCredenceByTokenRequest request) {
            return base.Channel.GetCredenceByToken(request);
        }
        
        public object GetCredenceByToken(string token) {
            testLXJ.PassportService.GetCredenceByTokenRequest inValue = new testLXJ.PassportService.GetCredenceByTokenRequest();
            inValue.Body = new testLXJ.PassportService.GetCredenceByTokenRequestBody();
            inValue.Body.token = token;
            testLXJ.PassportService.GetCredenceByTokenResponse retVal = ((testLXJ.PassportService.PassportServiceSoap)(this)).GetCredenceByToken(inValue);
            return retVal.Body.GetCredenceByTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testLXJ.PassportService.ClearPCertResponse testLXJ.PassportService.PassportServiceSoap.ClearPCert(testLXJ.PassportService.ClearPCertRequest request) {
            return base.Channel.ClearPCert(request);
        }
        
        public void ClearPCert(string token) {
            testLXJ.PassportService.ClearPCertRequest inValue = new testLXJ.PassportService.ClearPCertRequest();
            inValue.Body = new testLXJ.PassportService.ClearPCertRequestBody();
            inValue.Body.token = token;
            testLXJ.PassportService.ClearPCertResponse retVal = ((testLXJ.PassportService.PassportServiceSoap)(this)).ClearPCert(inValue);
        }
    }
}
